---
cpcgan:
    batch_size: 64
    color: False
    image_shape: [28, 28, 3]
    code_size: 64   
    gan_coeff: 1    # coefficient for gan loss ,train weight
    cpc_coeff: 10   # coefficient for cpc loss,train weight

    # model path: os.path.join(model_root_dir, model_dir, model_name)
    # tensorboard path: os.path.join(tensorboard_root_dir, model_dir, model_name)
    # each one should have his own *_root_dir to avoid conflict
    model_root_dir: '/tmp/cpcgan/saved_models'
    tensorboard_root_dir: '/tmp/cpcgan/tensorboard_logs'
    model_dir: Day2
    model_name: lr_1e-4
    cpc:
        learning_rate: 0.0001
        weight_decay: 0.0001
        context_size: 256  #rnn gru cell size
        hist_terms: 4
        future_terms: 4
    gan:
        learning_rate: 0.0001
        weight_decay: 0.0001
        noise_size: 10  #noise dim
        critic_coeff: 1.  # weight