---
cpc:
    learning_rate: 0.001
    weight_decay: 0.0001
    code_size: 128

WGANGP:
    image_shape: [28, 28, 3]
    code_size: 10
    predict_terms: 1
    batch_size: 128
    coeff: 1.
batch_size: 128

model_name: supervised
